# Generated by Django 5.2.8 on 2025-11-27 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDetails',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('case_category', models.CharField(max_length=100)),
                ('court_level', models.CharField(max_length=100)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('urgency', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('case_description', models.TextField()),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
