# Generated by Django 5.2.8 on 2025-12-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=191, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('fee', models.IntegerField()),
                ('about', models.TextField()),
                ('documents', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LawyerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=191, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('fee', models.IntegerField()),
                ('about', models.TextField()),
                ('documents', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
