# Generated by Django 5.2.8 on 2025-12-05 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lawyers', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyerprofile',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.city'),
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='courts',
            field=models.ManyToManyField(to='users.court'),
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='fee_band',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.feeband'),
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='languages',
            field=models.ManyToManyField(to='users.language'),
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='practice_areas',
            field=models.ManyToManyField(to='users.subcategory'),
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matter',
            name='court',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.court'),
        ),
        migrations.AddField(
            model_name='matter',
            name='fee_band',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.feeband'),
        ),
        migrations.AddField(
            model_name='matter',
            name='lawyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matters', to='lawyers.lawyerprofile'),
        ),
        migrations.AddField(
            model_name='matter',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.subcategory'),
        ),
        migrations.AddField(
            model_name='verificationdocument',
            name='lawyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawyers.lawyerprofile'),
        ),
    ]
