# Generated by Django 5.2.8 on 2025-12-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='lawyer_pics/'),
        ),
        migrations.AddField(
            model_name='lawyerrequest',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='lawyer_pics/'),
        ),
    ]
