# Generated by Django 5.2.8 on 2025-12-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyerprofile',
            name='languages',
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
